//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 08:15:54 PM GMT+04:00 
//


package com.exactpro.sf.common.impl.messages.all.configuration.sample;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for JavaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JavaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="java.lang.Boolean"/>
 *     &lt;enumeration value="java.lang.Short"/>
 *     &lt;enumeration value="java.lang.Integer"/>
 *     &lt;enumeration value="java.lang.Long"/>
 *     &lt;enumeration value="java.lang.Byte"/>
 *     &lt;enumeration value="java.lang.Float"/>
 *     &lt;enumeration value="java.lang.Double"/>
 *     &lt;enumeration value="java.lang.String"/>
 *     &lt;enumeration value="java.time.LocalDateTime"/>
 *     &lt;enumeration value="java.time.LocalDate"/>
 *     &lt;enumeration value="java.time.LocalTime"/>
 *     &lt;enumeration value="java.lang.Character"/>
 *     &lt;enumeration value="java.math.BigDecimal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "JavaType")
@XmlEnum
public enum JavaType
{

    @XmlEnumValue("java.lang.Boolean")
    JAVA_LANG_BOOLEAN("java.lang.Boolean"),
    @XmlEnumValue("java.lang.Short")
    JAVA_LANG_SHORT("java.lang.Short"),
    @XmlEnumValue("java.lang.Integer")
    JAVA_LANG_INTEGER("java.lang.Integer"),
    @XmlEnumValue("java.lang.Long")
    JAVA_LANG_LONG("java.lang.Long"),
    @XmlEnumValue("java.lang.Byte")
    JAVA_LANG_BYTE("java.lang.Byte"),
    @XmlEnumValue("java.lang.Float")
    JAVA_LANG_FLOAT("java.lang.Float"),
    @XmlEnumValue("java.lang.Double")
    JAVA_LANG_DOUBLE("java.lang.Double"),
    @XmlEnumValue("java.lang.String")
    JAVA_LANG_STRING("java.lang.String"),
    @XmlEnumValue("java.time.LocalDateTime")
    JAVA_TIME_LOCAL_DATE_TIME("java.time.LocalDateTime"),
    @XmlEnumValue("java.time.LocalDate")
    JAVA_TIME_LOCAL_DATE("java.time.LocalDate"),
    @XmlEnumValue("java.time.LocalTime")
    JAVA_TIME_LOCAL_TIME("java.time.LocalTime"),
    @XmlEnumValue("java.lang.Character")
    JAVA_LANG_CHARACTER("java.lang.Character"),
    @XmlEnumValue("java.math.BigDecimal")
    JAVA_MATH_BIG_DECIMAL("java.math.BigDecimal");
    private final String value;

    JavaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JavaType fromValue(String v) {
        for (JavaType c: JavaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
