//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 08:15:54 PM GMT+04:00 
//


@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://exactprosystems.com/dictionary",
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.exactpro.sf.common.impl.messages.xml.configuration;