-- This empty script was created to mark database version that can be migrated to Sailfish 3.2
-- To upgrade Flyway version from 3.2.1 to 5.2.1 we must upgrade to Flyway 4.2.0 first
-- https://flywaydb.org/documentation/releaseNotes#5.0.0