<link rel="stylesheet" type="text/css" href="../resources/static-help.css"/>
<span class="eps-content-value" >
	<h2>Actions class information:</h2>
	<table class='eps-content-message-table'>
		<tr><td>Description</td><td>${description}</td></tr>
		<tr><td>Aliases</td><td>${aliases}</td></tr>
		<tr><td>URI</td><td>${uri}</td></tr>
		<tr><td>Methods count</td><td>${methodsCount}</td></tr>
	</table>
</span>
