ALTER TABLE stactions ALTER COLUMN name SET NOT NULL;
ALTER TABLE stenvironments ALTER COLUMN name SET NOT NULL;
ALTER TABLE stmatrices ALTER COLUMN name SET NOT NULL;

ALTER TABLE stmessagetypes ALTER COLUMN name SET NOT NULL;
ALTER TABLE stservices ALTER COLUMN name SET NOT NULL;
ALTER TABLE sttestcases ALTER COLUMN testcaseid SET NOT NULL;